sudo: required
language: node_js
node_js:
  - "node"

branches:
  only:
    - develop

services:
  - docker

before_install:
  - docker-compose -f docker-compose-development.yml up -d
  - docker ps -a

script:
  - docker-compose -f docker-compose-development.yml run web npm run test
  - docker-compose -f docker-compose-development.yml stop
  - docker ps -a

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    docker build -t apinf/platform:$DOCKER_TAG .
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push apinf/platform:$DOCKER_TAG
    fi
