sudo: false
language: node_js
node_js:
  - "node"

branches:
  only:
    - develop

services:
  - docker

before_install:
  - "curl https://install.meteor.com | /bin/sh"

script:
  - ./.scripts/test.sh && ./.scripts/docker_build.sh
