sudo: false
language: node_js
node_js:
  - "node"

branches:
  only:
    - develop

services:
  - docker

before_script:
  - npm run-script lint
  - npm run-script test-phantom
  - npm run-script test-app-phantom

script:
  - ./.scripts/docker_build.sh
